dtksh: Upgrade ksh93 to 1.0.0-beta.2 2021-12-28
Patch from current ksh93 maintainer <https://github.com/ksh93/ksh>.

cde/programs/dtksh/ksh93/**:
- Upgraded. A load of bugs fixed, some minor features added.
  See NEWS from 2021-02-01 upwards.

cde/programs/dtksh/Makefile.am:
- Don't cd into ksh93 any more to invoke the package or shtests
  scripts; they now automatically find their directories.
- Pass $(CFLAGS) to build ksh with optimisation.
- Remove -D_std_malloc flag as vmalloc is now deprecated and disabled
  by default.
- Add a 'make check' target to Makefile.am that runs the ksh93
  regression tests on dtksh to make sure the additions don't interfere
  with anything. It skips running the tests with shcomp because CDE
  doesn't use that. The tests all pass here on Slackware 14.2. :-)

cde/programs/dtksh/init.patch:
- Removed; I've upstreamed it. It was the only one that wasn't upstreamed
  yet, and more code cleanups are coming, breaking downstream patches. If
  something needs updating, just email me a diff.

cde/programs/dtksh/dtkcmds.h:
- Update the ADDBUILTIN macro to remove the __PROTO__ macro use. The
  proto(1) tool, responsible for all such pre-C89 K&R C compatibility
  voodoo, has been removed, so that macro is no longer defined.

cde/programs/dtksh/setup.sh:
- Workaround script removed. I rewrote 'bin/package flat make' in a way
  that works correctly and changed Makefile.am to use that instead.

Hope this helps. Happy new year.

diff --git a/cde/programs/dtksh/ksh93/src/cmd/builtin/features/pty b/cde/programs/dtksh/ksh93/src/cmd/builtin/features/pty
--- a/cde/programs/dtksh/ksh93/src/cmd/builtin/features/pty
+++ b/cde/programs/dtksh/ksh93/src/cmd/builtin/features/pty
@@ -1,5 +1,3 @@
-set	prototyped
-
 header	sys/types.h
 header	pty.h
 header	libutil.h
@@ -13,7 +11,7 @@ lib	openpty,_getpty,ptsname -lutil
 lib	grantpt,unlockpt,posix_openpt stdlib.h
 lib	cfmakeraw termios.h
 
-tst - output{
+tst - -lm output{
 	#include	<fcntl.h>
 	#if _lib_ptsname
 	#include	<stdlib.h>
@@ -52,7 +50,8 @@ tst - output{
 		return 0;
 	}
 }end fail{
-	echo '#error The output block in src/cmd/builtin/features/pty failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 extern	_getpty		char*		(int*, int, mode_t, int)
diff --git a/cde/programs/dtksh/ksh93/src/lib/libast/features/common b/cde/programs/dtksh/ksh93/src/lib/libast/features/common
--- a/cde/programs/dtksh/ksh93/src/lib/libast/features/common
+++ b/cde/programs/dtksh/ksh93/src/lib/libast/features/common
@@ -1,5 +1,5 @@
 iff	AST_COMMON
-hdr	pthread,stdarg,stddef,stdint,inttypes,types,unistd
+hdr	pthread,stdarg,stddef,stdint,stdnoreturn,inttypes,types,unistd
 sys	types
 typ	long.double,size_t,ssize_t
 typ	__va_list stdio.h
@@ -24,79 +24,42 @@ tst	ptr_void note{ standard C void* ok }end compile{
 }end
 
 cat{
+	#pragma clang diagnostic ignored "-Wdeprecated-register"
 	#pragma clang diagnostic ignored "-Wmacro-redefined"
 	#pragma clang diagnostic ignored "-Wparentheses"
+	#pragma clang diagnostic ignored "-Wstring-plus-int"
 	#pragma clang diagnostic ignored "-Wunused-value"
 
-	/* disable non-standard linux/gnu inlines */
+	/* AST backwards compatibility macros */
+	#undef	_NIL_
+	#define	_NIL_(x)	((x)0)
+	#undef	_STD_
+	#define	_STD_		1
+	#undef	_ARG_
+	#define	_ARG_(x)	x
+	#undef	_VOID_
+	#define	_VOID_		void
+	#undef	_BEGIN_EXTERNS_
+	#define	_BEGIN_EXTERNS_
+	#undef	_END_EXTERNS_
+	#define	_END_EXTERNS_
+	#undef	__STD_C
+	#define	__STD_C		1
+	#undef	Void_t
+	#define	Void_t		void
+
+	/* disable non-standard Linux/GNU inlines */
 	#ifdef __GNUC__	
 	#	undef	__OPTIMIZE_SIZE__
 	#	define	__OPTIMIZE_SIZE__	1
 	#endif
 
-	/* enable POSIX standard on Solaris */
-	#ifdef __sun
-	#	undef	_XPG6
-	#	define	_XPG6		1
-	#endif
-
-	/* __STD_C indicates that the language is ANSI-C or C++ */
-	#if !defined(__STD_C) && __STDC__
-	#	define	__STD_C		1
-	#endif
-	#if !defined(__STD_C) && (__cplusplus || c_plusplus)
-	#	define __STD_C		1
-	#endif
-	#if !defined(__STD_C) && _std_proto
-	#	define __STD_C		1
-	#endif
-	#if !defined(__STD_C)
-	#	define __STD_C		0
-	#endif
-
-	/* extern symbols must be protected against C++ name mangling */
-	#ifndef _BEGIN_EXTERNS_
-	#	if __cplusplus || c_plusplus
-	#		define _BEGIN_EXTERNS_	extern "C" {
-	#		define _END_EXTERNS_	}
-	#	else
-	#		define _BEGIN_EXTERNS_
-	#		define _END_EXTERNS_
-	#	endif
-	#endif
-
-	/* _ARG_ simplifies function prototyping among flavors of C */
-	#ifndef _ARG_
-	#	if __STD_C
-	#		define _ARG_(x)	x
-	#	else
-	#		define _ARG_(x)	()
-	#	endif
-	#endif
-
-	/* _NIL_ simplifies defining nil pointers to a given type */
-	#ifndef _NIL_
-	#	define _NIL_(x)	((x)0)
-	#endif
-
 	/* __INLINE__, if defined, is the inline keyword */
-	#if !defined(__INLINE__) && defined(__cplusplus)
-	#	define __INLINE__	inline
-	#endif
 	#if !defined(__INLINE__) && defined(_WIN32) && !defined(__GNUC__)
 	#	define __INLINE__	__inline
 	#endif
 
-	/* Void_t is defined so that Void_t* can address any type */
-	#ifndef Void_t
-	#	if __STD_C
-	#		define Void_t		void
-	#	else
-	#		define Void_t		char
-	#	endif
-	#endif
-
-	/* windows variants and veneers */
+	/* Windows variants and veneers */
 	#if !defined(_WINIX) && (_UWIN || __CYGWIN__ || __EMX__)
 	#	define _WINIX		1
 	#endif
@@ -134,17 +97,22 @@ cat{
 	#	endif
 	#endif
 	#if _dll_import && ( !_BLD_DLL || _WINIX && !_UWIN )
-	#	ifdef __STDC__
 	#	define __EXTERN__(T,obj)	extern T obj; T* _imp__ ## obj = &obj
 	#	define __DEFINE__(T,obj,val)	T obj = val; T* _imp__ ## obj = &obj
-	#	else
-	#	define __EXTERN__(T,obj)	extern T obj; T* _imp__/**/obj = &obj
-	#	define __DEFINE__(T,obj,val)	T obj = val; T* _imp__/**/obj = &obj
-	#	endif
 	#else
 	#	define __EXTERN__(T,obj)	extern T obj
 	#	define __DEFINE__(T,obj,val)	T obj = val
 	#endif
+
+	#if !_hdr_stdnoreturn
+	#if defined(__GNUC__) && (__GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ > 4))
+	#define noreturn __attribute__((noreturn))
+	#else
+	#define noreturn
+	#endif /* __GNUC__ */
+	#else
+	#include <stdnoreturn.h>
+	#endif /* _hdr_stdnoreturn */
 }end
 
 if	tst - note{ <stdarg.h>+<wchar.h> works }end compile{
@@ -173,7 +141,6 @@ tst	- -DN=1 - -DN=2 - -DN=3 - -DN=4 - -DN=5 - -DN=6 - -DN=7 - -DN=8 - -DN=0 outp
 	#include <string.h>
 	#include <sys/types.h>
 
-	#if _STD_
 	#if N == 1
 	#define _ast_int8_t	long
 	#define _ast_int8_str	"long"
@@ -205,7 +172,6 @@ tst	- -DN=1 - -DN=2 - -DN=3 - -DN=4 - -DN=5 - -DN=6 - -DN=7 - -DN=8 - -DN=0 outp
 	#if N == 8
 	#define _ast_int8_t	int64
 	#define _ast_int8_str	"int64"
-	#endif
 	#endif
 
 	#define elementsof(x)	(sizeof(x)/sizeof(x[0]))
@@ -353,7 +319,8 @@ tst	- output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #2 in src/lib/libast/features/common failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- -DN=1 - -DN=0 output{
@@ -362,7 +329,7 @@ tst	- -DN=1 - -DN=0 output{
 	#include <string.h>
 	#include <sys/types.h>
 
-	#if !N || !_STD_
+	#if !N
 	#undef	_typ_long_double
 	#endif
 
@@ -477,7 +444,7 @@ typ uintptr_t stdint.h inttypes.h no{
 }end
 
 tst	- -DTRY=1 - -DTRY=1 -Dvoid=char - -DTRY=2 - -DTRY=3 - -DTRY=4 output{
-	#if _STD_ && _hdr_stdarg
+	#if _hdr_stdarg
 	#include <stdarg.h>
 	static void
 	varyfunny(int* p, ...)
@@ -524,11 +491,7 @@ tst	- -DTRY=1 - -DTRY=1 -Dvoid=char - -DTRY=2 - -DTRY=3 - -DTRY=4 output{
 
 		printf("\n#ifndef va_listref\n");
 		printf("#ifndef	va_start\n");
-		printf("#if __STD_C\n");
 		printf("#include <stdarg.h>\n");
-		printf("#else\n");
-		printf("#include <varargs.h>\n");
-		printf("#endif\n");
 		printf("#endif\n");
 	#if TRY == 4
 		printf("#define va_listref(p) (&(p))\t");
@@ -589,7 +552,7 @@ tst	- -DTRY=1 - -DTRY=1 -Dvoid=char - -DTRY=2 - -DTRY=3 - -DTRY=4 output{
 
 cat{
 	#ifndef _AST_STD_H
-	#	if __STD_C && _hdr_stddef
+	#	if _hdr_stddef
 	#	include	<stddef.h>
 	#	endif
 	#	if _sys_types
@@ -633,4 +596,38 @@ run{
 	#define __name_h		1
 	#endif
 	!
+}end
+
+tst - note{ does this compiler have __builtin_unreachable() }end output{
+	/*
+	 * To avoid optimizing out the __builtin_unreachable() test call while also avoiding
+	 * executing it, put it in a test function that is called with argc as the argument.
+	 * argc should never be zero on init, but hopefully optimizers aren't that smart.
+	 */
+	#include <stdio.h>
+	void testfn(int a)
+	{
+		switch(a)
+		{
+		case 0:
+			__builtin_unreachable();
+		default:
+			printf("#if _AST_ksh_release\n");
+			printf("#   define UNREACHABLE()\t__builtin_unreachable()\n");
+			printf("#else\n");
+			printf("#   define UNREACHABLE()\tabort()\n");
+			printf("#endif\n");
+		}
+	}
+	int main(int argc, char *argv[])
+	{
+		testfn(argc);
+		return 0;
+	}
+}end fail{
+	echo '#if _AST_ksh_release'
+	echo '#   define UNREACHABLE()	0'
+	echo '#else'
+	echo '#   define UNREACHABLE()	abort()'
+	echo '#endif'
 }end
diff --git a/cde/programs/dtksh/ksh93/src/lib/libast/features/float b/cde/programs/dtksh/ksh93/src/lib/libast/features/float
--- a/cde/programs/dtksh/ksh93/src/lib/libast/features/float
+++ b/cde/programs/dtksh/ksh93/src/lib/libast/features/float
@@ -1,8 +1,7 @@
-set	prototyped
 set	nooptimize
 set	stdio FEATURE/standards
 hdr	float,limits,math,values
-lib,npt	frexp,frexpl,ldexp,ldexpl,finite,finitel,isinfl,isnanl,copysign,copysignl FEATURE/standards math.h -lm
+lib,npt	frexp,frexpl,ldexp,ldexpl,finite,finitel,isinfl,isnanl,copysign,copysignl,powf,pow,powl FEATURE/standards math.h -lm
 lib	fpclassify -lm note{ fpclassify present and works }end link{
 		#include <sys/types.h>
 		#include <sys/stat.h>
@@ -261,11 +260,7 @@ tst	- note{ missing floating point limits }end output{
 	#include <signal.h>
 	#ifdef SIGFPE
 	static int caught = 0;
-	#if _STD_
 	static void catch(int sig)
-	#else
-	static void catch(sig) int sig;
-	#endif
 	{
 		signal(sig, SIG_IGN);
 		caught++;
@@ -895,7 +890,8 @@ tst	- note{ missing floating point limits }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- note{ double exponent bitfoolery }end output{
@@ -931,7 +927,8 @@ tst	- note{ double exponent bitfoolery }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- note{ long double exponent bitfoolery }end output{
@@ -967,7 +964,8 @@ tst	- note{ long double exponent bitfoolery }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- -DN=1 - -DN=2 note{ _ast_fltmax_t maximum integral type }end output{
@@ -1025,15 +1023,7 @@ tst	- -DSCAN=1 - -lm -DSTRTO=1 - -DMAC=1 - -DDIV=1 - -DEXP=1 - -DADD=1 - -DMPY=1
 	#undef	LDBL_MAX
 	#endif
 	static void
-	#if _STD_
 	list(const char* typ, const char* var, void* val, int siz)
-	#else
-	list(typ, var, val, siz)
-	char* typ;
-	char* var;
-	void* val;
-	int siz;
-	#endif
 	{
 		register unsigned char*	u = (unsigned char*)val;
 		register unsigned char*	e = u + siz;
@@ -1230,3 +1220,34 @@ tst	- -DSCAN=1 - -lm -DSTRTO=1 - -DMAC=1 - -DDIV=1 - -DEXP=1 - -DADD=1 - -DMPY=1
 		return 0;
 	}
 }end
+
+if	need_ast_pow_macros -lm note{ are IEEE pow macro replacements needed }end execute{
+	#include <sys/types.h>
+	#include <sys/stat.h>
+	#include <stdlib.h>
+	#include <unistd.h>
+	#include <math.h>
+	int main() { return pow(1.0, 1.0 / 0.0) == 1.0; }
+}end {
+	#define powf(x,y)	(((x)==1.0)?1.0:powf((x),(y)))
+	#define pow(x,y)	(((x)==1.0)?1.0:pow((x),(y)))
+	#define powl(x,y)	(((x)==1.0)?1.0:powl((x),(y)))
+}
+elif	tst need_ast_pow_funs -lm note{ are IEEE pow function replacements needed }end execute{
+	#include <sys/types.h>
+	#include <sys/stat.h>
+	#include <stdlib.h>
+	#include <unistd.h>
+	#include <math.h>
+	/* This bit of obfuscation defeats GCC's code optimizer. */
+	double (*volatile _ast_ppow)(double,double);
+	int main () { _ast_ppow = &pow; return (*_ast_ppow)(1.0, 1.0 / 0.0) == 1.0; }
+}end {
+	float			_ast_powf(float x, float y);
+	double			_ast_pow(double x, double y);
+	long double		_ast_powl(long double x, long double y);
+	#define powf(x,y)	(_ast_powf((x),(y)))
+	#define pow(x,y)	(_ast_pow((x),(y)))
+	#define powl(x,y)	(_ast_powl((x),(y)))
+}
+endif
diff --git a/cde/programs/dtksh/ksh93/src/lib/libast/features/lib b/cde/programs/dtksh/ksh93/src/lib/libast/features/lib
--- a/cde/programs/dtksh/ksh93/src/lib/libast/features/lib
+++ b/cde/programs/dtksh/ksh93/src/lib/libast/features/lib
@@ -4,8 +4,13 @@ cmd	universe
 
 hdr	dirent,direntry,filio,fmtmsg,fnmatch,jioctl,libgen,limits
 hdr	locale,ndir,nl_types,process,spawn,syslog,utime,vfork
+hdr	linux/fs,linux/msdos_fs,sys/ioctl
+hdr	wctype
 hdr	wchar note{ <wchar.h> and isw*() really work }end execute{
 	#include <wchar.h>
+	#if _hdr_wctype
+	#include <wctype.h>
+	#endif
 	int
 	main()
 	{
@@ -13,7 +18,6 @@ hdr	wchar note{ <wchar.h> and isw*() really work }end execute{
 		return iswalnum(w) == 0;
 	}
 }end
-hdr	wctype wchar.h
 
 dat	_tzname,tzname
 
@@ -28,7 +32,7 @@ lib	getopt,getsubopt,getopt_long,getopt_long_only
 lib	glob,index,iswblank,iswctype,killpg,link,localeconv,madvise
 lib	mbtowc,mbrtowc,memalign,memchr,memcpy,memdup,memmove,memset
 lib	mkdir,mkfifo,mktemp,mktime
-lib	mount,on_exit,onexit,opendir,pathconf
+lib	mount,onexit,opendir,pathconf
 lib	readlink,remove,rename,rewinddir,rindex,rmdir,setlocale
 lib	setpgid,setpgrp,setpgrp2,setreuid,setsid,setuid,sigaction
 lib	sigprocmask,sigsetmask,sigunblock,sigvec,socketpair
@@ -37,9 +41,9 @@ lib	strchr,strcoll,strdup,strerror,strcasecmp,strncasecmp,strrchr,strstr
 lib	strmode,strxfrm,strftime,swab,symlink,sysconf,sysinfo,syslog
 lib	telldir,tmpnam,tzset,universe,unlink,utime,wctype
 lib	ftruncate,truncate
-lib	creat64,fstat64,fstatvfs64,ftruncate64 -D_LARGEFILE64_SOURCE
-lib	lseek64,lstat64 -D_LARGEFILE64_SOURCE
-lib	open64,readdir64,stat64,statvfs64,truncate64 -D_LARGEFILE64_SOURCE
+lib	creat64,fstat64,fstatvfs64,ftruncate64
+lib	lseek64,lstat64
+lib	open64,readdir64,stat64,statvfs64,truncate64
 
 lib,npt	strtod,strtold,strtol,strtoll,strtoul,strtoull stdlib.h
 lib,npt	sigflag signal.h
@@ -53,11 +57,10 @@ mem	inheritance.pgroup spawn.h
 sys	dir,filio,jioctl,localedef,ptem,resource
 sys	socket,stream,systeminfo,universe,vfork
 
-typ	ino64_t,off64_t -D_LARGEFILE64_SOURCE
-typ	struct.dirent64 -D_LARGEFILE64_SOURCE dirent.h
+typ	ino64_t,off64_t
+typ	struct.dirent64 dirent.h
 
 tst	tst_errno note{ errno can be assigned }end link{
-	_BEGIN_EXTERNS_
 	#define error		______error
 	#define strerror	______strerror
 	#include <errno.h>
@@ -68,15 +71,13 @@ tst	tst_errno note{ errno can be assigned }end link{
 	#endif
 	error() { }
 	strerror() { }
-	_END_EXTERNS_
 	int main() { errno = 0; error(); strerror(); return 0; }
 }end
 
 tst	lib_poll_fd_1 note{ fd is first arg to poll() }end execute{
 	#include <poll.h>
-	_BEGIN_EXTERNS_
-	extern int	pipe _ARG_((int*));
-	_END_EXTERNS_
+	#include <unistd.h>
+	extern int	pipe(int*);
 	int
 	main()
 	{	int		rw[2];
@@ -94,9 +95,8 @@ tst	lib_poll_fd_1 note{ fd is first arg to poll() }end execute{
 
 tst	lib_poll_fd_2 note{ fd is second arg to poll() }end execute{
 	#include <poll.h>
-	_BEGIN_EXTERNS_
-	extern int	pipe _ARG_((int*));
-	_END_EXTERNS_
+	#include <unistd.h>
+	extern int	pipe(int*);
 	int
 	main()
 	{	int		rw[2];
@@ -118,9 +118,7 @@ exp	_lib_poll	_lib_poll_fd_1||_lib_poll_fd_2
 tst	lib_poll_notimer note{ poll with no fds ignores timeout }end execute{
 	#include <sys/types.h>
 	#include <poll.h>
-	_BEGIN_EXTERNS_
-	extern time_t	time _ARG_((time_t*));
-	_END_EXTERNS_
+	extern time_t	time(time_t*);
 	#define TIMEOUT		4
 	int
 	main()
@@ -169,12 +167,10 @@ tst	sys_select note{ select() requires <sys/select.h> }end link{
 }end
 
 tst	pipe_rw note{ full duplex pipes }end execute{
-	_BEGIN_EXTERNS_
-	extern int	pipe _ARG_((int*));
-	extern int	read _ARG_((int, void*, int));
-	extern int	strcmp _ARG_((const char*, const char*));
-	extern int	write _ARG_((int, void*, int));
-	_END_EXTERNS_
+	extern int	pipe(int*);
+	extern int	read(int, void*, int);
+	extern int	strcmp(const char*, const char*);
+	extern int	write(int, void*, int);
 	int
 	main()
 	{
@@ -199,6 +195,7 @@ tst	pipe_rw note{ full duplex pipes }end execute{
 
 tst	lib_vfork unistd.h stdlib.h vfork.h note{ vfork exists and it works }end execute{
 	#include <signal.h>
+	#include <sys/wait.h>
 	int
 	main(argc, argv)
 	int	argc;
@@ -226,10 +223,8 @@ tst	lib_vfork unistd.h stdlib.h vfork.h note{ vfork exists and it works }end exe
 }end
  
 tst	real_vfork note{ vfork child shares data with parent }end execute{
-	_BEGIN_EXTERNS_
-	extern int	_exit _ARG_((int));
-	extern int	vfork _ARG_((void));
-	_END_EXTERNS_
+	extern int	_exit(int);
+	extern int	vfork(void);
 	int		code;
 	int
 	main()
@@ -251,9 +246,9 @@ tst	lib_posix_spawn unistd.h stdlib.h spawn.h -Dfork=______fork note{ posix_spaw
 	#include <string.h>
 	/* if it uses fork() why bother? */
 	#undef fork
-	pid_t fork _ARG_((void)) { NOTE("uses fork()"); return -1; }
-	pid_t _fork _ARG_((void)) { NOTE("uses _fork()"); return -1; }
-	pid_t __fork _ARG_((void)) { NOTE("uses __fork()"); return -1; }
+	pid_t fork(void)) { NOTE("uses fork()"; return -1; }
+	pid_t _fork(void)) { NOTE("uses _fork()"; return -1; }
+	pid_t __fork(void)) { NOTE("uses __fork()"; return -1; }
 	int
 	main(argc, argv)
 	int	argc;
@@ -433,7 +428,7 @@ tst	socket_peek note{ recv(MSG_PEEK) works on socketpair() }end execute{
 }end
 
 tst	lib_memcmp string.h note{ standard memcmp interface that works }end execute{
-	/* sgi again -- we're sick of being their regression test */
+	/* SGI again -- we're sick of being their regression test */
 	#define L	8
 	char		a[L] = { '0' };
 	char		b[L] = { '1' };
@@ -445,21 +440,16 @@ tst	lib_memcmp string.h note{ standard memcmp interface that works }end execute{
 }end
 
 tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat.h sys/mman.h fcntl.h note{ standard memccpy interface that works }end execute{
-	#if _STD_
-	static void gotcha(int sig)
-	#else
-	static int gotcha(sig) int sig;
+	#ifndef MAP_FAILED
+	#define MAP_FAILED ((void*)-1)	/* introduced in POSIX-1.2017 */
 	#endif
+	static void gotcha(int sig)
 	{
 		exit(1);
 	}
 	#ifdef MAP_PRIVATE
 	static const char x[] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxN";
-	#if _STD_
 	static int indict_sgi_ia64_4Q_2004(int n)
-	#else
-	static int indict_sgi_ia64_4Q_2004(n) int n;
-	#endif
 	{
 		char*		b;
 		char*		s;
@@ -489,7 +479,7 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 			return 1;
 		}
 		m = n * (sizeof(x)-1);
-		if (!(b = mmap((void*)0, m, PROT_READ|PROT_WRITE, MAP_PRIVATE, d, (off_t)0)))
+		if ((b = mmap((void*)0, m, PROT_READ|PROT_WRITE, MAP_PRIVATE, d, (off_t)0)) == MAP_FAILED)
 		{
 			close(d);
 			return 1;
@@ -532,7 +522,7 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 	#endif
 	
 		/*
-		 * early mac osx failed here -- fixed 3Q 2001
+		 * early Mac OS X failed here -- fixed 3Q 2001
 		 */
 
 		if (memccpy(buf, "abc", 0, sizeof(buf)) != (buf + 4))
@@ -543,9 +533,9 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 			return 0;
 		if ((fd = open("/dev/zero", O_RDWR)) < 0)
 			return 0;
-		if (!(srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)))
+		if ((srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)) == MAP_FAILED)
 			return 0;
-		if (!mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0))
+		if (mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0) == MAP_FAILED)
 			return 0;
 		for (i = 0; i < siz; i++)
 			srcbuf[i] = 'x';
@@ -555,7 +545,7 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 		signal(SIGBUS, gotcha);
 		signal(SIGALRM, gotcha);
 		/*
-		 * sgi ia64 dumps here as of 3Q 2001
+		 * SGI ia64 dumps here as of 3Q 2001
 		 * bug acknowledged 1Q 2003
 		 */
 		memccpy(dstbuf, srcbuf, 0, siz + 10);
@@ -573,9 +563,7 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 
 tst	lib_utime_now note{ utime works with 0 time vector }end execute{
 	#include <sys/types.h>
-	_BEGIN_EXTERNS_
-	extern int	utime _ARG_((const char*, void*));
-	_END_EXTERNS_
+	extern int	utime(const char*, void*);
 	int
 	main()
 	{
@@ -596,32 +584,22 @@ tst	cross{
 }end
 
 std	cleanup note{ stuck with standard _cleanup }end noexecute{
-	_BEGIN_EXTERNS_
-	extern void exit _ARG_((int));
-	extern void _exit _ARG_((int));
+	extern void exit(int);
+	extern void _exit(int);
 	extern void _cleanup();
 	void _cleanup() { _exit(0); }
-	_END_EXTERNS_
 	int main() { printf("cleanup\n"); exit(1); }
 }end
 
 std	remove note{ stuck with standard remove() }end nostatic{
-	_BEGIN_EXTERNS_
-	extern int unlink _ARG_((const char*));
-	_END_EXTERNS_
-	#if _STD_
+	extern int unlink(const char*);
 	int remove(const char* path) { return 0; }
-	#else
-	int remove(path) char* path; { return 0; }
-	#endif
 	int main() { return unlink("foo"); }
 }end
 
 std	signal note{ stuck with standard signal }end nolink{
-	_BEGIN_EXTERNS_
 	extern int abort();
 	int signal() { return 0; }
-	_END_EXTERNS_
 	int main() { signal(); abort(); return 0; }
 }end
 
@@ -638,37 +616,18 @@ std	strcoll note{ standard strcoll works }end execute{
 }end
 
 std	strtod stdlib.h note{ stuck with standard strtod }end nostatic{
-	_BEGIN_EXTERNS_
-	#if _STD_
 	double strtod(const char* s, char** e) { return 0.0; }
-	#else
-	double strtod(s, e) char* s; char** e; { return 0.0; }
-	#endif
-	_END_EXTERNS_
 	int main() { printf(""); return strtod("1",0) != 0; }
 }end
 
 std	strtold stdlib.h note{ stuck with standard strtold }end nostatic{
-	_BEGIN_EXTERNS_
-	#if _STD_
 	long double strtold(const char* s, char** e) { return 0.0; }
-	#else
-	long double strtold(s, e) char* s; char** e; { return 0.0; }
-	#endif
-	_END_EXTERNS_
 	int main() { printf(""); return strtold("1",0) != 0; }
 }end
 
 std	strtol note{ stuck with standard strtol }end nostatic{
-	_BEGIN_EXTERNS_
-	#if _STD_
 	extern long atol(const char*);
 	long strtol(const char* s, char** e, int b) { return 0; }
-	#else
-	extern long atol();
-	long strtol(s, e, b) char* s; char** e; int b; { return 0; }
-	#endif
-	_END_EXTERNS_
 	int main() { printf(""); return (atol("1") + strtol("1",(char**)0,0)) != 0; }
 }end
 
@@ -678,7 +637,7 @@ tst	- output{
 	{
 	#if _UWIN
 		printf("\n");
-		printf("/* override some uwin feature tests */\n");
+		printf("/* override some UWIN feature tests */\n");
 		printf("#undef	_lib_execlp\n");
 		printf("#undef	_lib_execvp\n");
 		printf("#undef	_lib_execvpe\n");
@@ -700,10 +659,11 @@ tst	- output{
 	}
 
 }end fail{
-	echo '#error The output block in src/lib/libast/features/lib failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
-tst	no64 -D_LARGEFILE64_SOURCE note{ largefile 64 broken }end execute{
+tst	no64 note{ largefile 64 broken }end execute{
 	#include <sys/types.h>
 	#include <sys/stat.h>
 	int
@@ -726,7 +686,7 @@ tst	no64 -D_LARGEFILE64_SOURCE note{ largefile 64 broken }end execute{
 	echo "#undef	_lib_truncate64"
 }end
 
-tst	need64 -D_LARGEFILE64_SOURCE note{ off64_t necessary }end nocompile{
+tst	need64 note{ off64_t necessary }end nocompile{
 	#include <sys/types.h>
 	typedef off64_t __ast_off64_t__;
 	typedef off_t __ast_off_t__;
diff --git a/cde/programs/dtksh/ksh93/src/lib/libast/features/sfio b/cde/programs/dtksh/ksh93/src/lib/libast/features/sfio
--- a/cde/programs/dtksh/ksh93/src/lib/libast/features/sfio
+++ b/cde/programs/dtksh/ksh93/src/lib/libast/features/sfio
@@ -15,7 +15,8 @@ tst	- note{ number of bits in pointer }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error The output block in src/lib/libast/features/sfio failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	tmp_rmfail note{ open files cannot be removed }end execute{
@@ -114,11 +115,9 @@ tst	vax_asm note{ register layout ok for vax string operations }end execute{
 }end
 
 tst	lib_cvt note{ native floating point conversions ok }end link{
-	_BEGIN_EXTERNS_
-	extern char* ecvt _ARG_((double, int, int*, int*));
-	extern char* fcvt _ARG_((double, int, int*, int*));
-	extern double strtod _ARG_((const char*, char**));
-	_END_EXTERNS_
+	extern char* ecvt(double, int, int*, int*);
+	extern char* fcvt(double, int, int*, int*);
+	extern double strtod(const char*, char**);
 	int
 	main()
 	{
@@ -130,6 +129,8 @@ tst	lib_cvt note{ native floating point conversions ok }end link{
 }end
 
 tst	xopen_stdio note{ Stdio fseek/fflush are X/Open-compliant }end execute{
+	#include <fcntl.h>
+	#include <unistd.h>
 	#define Failed(file)	(unlink(file),1)
 	int
 	main(argc, argv)
diff --git a/cde/programs/dtksh/ksh93/src/lib/libdll/features/dll b/cde/programs/dtksh/ksh93/src/lib/libdll/features/dll
--- a/cde/programs/dtksh/ksh93/src/lib/libdll/features/dll
+++ b/cde/programs/dtksh/ksh93/src/lib/libdll/features/dll
@@ -1,4 +1,3 @@
-set	prototyped
 hdr	dl,dlfcn,dll,rld_interface,mach-o/dyld
 sys	ldr
 lib	dlopen -ldl
@@ -15,7 +14,7 @@ tst	dll_DYNAMIC link{
 }end
 tst	run{
 	lib=
-	for d in  /shlib /usr/shlib /lib /usr/lib
+	for d in  /lib64 /usr/lib64 /lib /usr/lib
 	do	if	test -d $d
 		then	for s in "*.*" "*[!a]*"
 			do	for b in libc
@@ -52,7 +51,7 @@ tst	run{
 	"")	lib=/lib/libc.so.1 ;;
 	esac
 	case $lib in
-	/usr/lib/*)
+	/usr/lib64/*|/usr/lib/*)
 		case `package` in
 		sgi.mips3)
 			abi=/lib32
@@ -65,7 +64,7 @@ tst	run{
 		esac
 		case $abi in
 		?*)	if	test -d $abi
-			then	lib=`echo $lib | sed 's,/usr/lib/,,'`
+			then	lib=`echo $lib | sed 's,/usr/lib\(64\)\?/,,'`
 				lib=$abi/$lib
 			fi
 			;;
@@ -74,7 +73,7 @@ tst	run{
 	esac
 	echo "#define _DLL_NEXT_PATH	\"$lib\""
 }end
-tst	- output{
+tst	- -lm output{
 	#include <math.h>
 	#if defined(__MVS__) && !defined(__SUSV3)
 	#define __SUSV3		1
@@ -262,5 +261,6 @@ tst	- output{
 		return 0;
 	}
 }end fail{
-	echo '#error The output block in src/lib/libdll/features/dll failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
